name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  job_build:
    name: Compilation for NanoS, X and S+

    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "$NANOS_SDK"
          - model: nanox
            SDK: "$NANOX_SDK"
          - model: nanosp
            SDK: "$NANOSP_SDK"

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make DEBUG=0 COIN=bitcoin BOLOS_SDK=${{ matrix.SDK }} && mv bin/ bitcoin-bin/
          make clean
          make DEBUG=0 COIN=bitcoin_testnet BOLOS_SDK=${{ matrix.SDK }} && mv bin/ bitcoin-testnet-bin/
          make clean
          make DEBUG=0 COIN=bitcoin_testnet_lib BOLOS_SDK=${{ matrix.SDK }} && mv bin/ bitcoin-testnet-lib-bin/
      - name: Upload Bitcoin app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-app-${{ matrix.model }}
          path: bitcoin-bin

      - name: Upload Bitcoin Testnet app binary
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-testnet-app-${{ matrix.model }}
          path: bitcoin-testnet-bin

      - name: Upload Bitcoin Testnet app binary (lib version)
        uses: actions/upload-artifact@v2
        with:
          name: bitcoin-testnet-lib-app-${{ matrix.model }}
          path: bitcoin-testnet-lib-bin

  job_unit_test:
    name: Unit test
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build unit tests
        run: |
          cd unit-tests/
          cmake -Bbuild -H. && make -C build && make -C build test
      - name: Generate code coverage
        run: |
          cd unit-tests/
          lcov --directory . -b "$(realpath build/)" --capture --initial -o coverage.base && \
          lcov --rc lcov_branch_coverage=1 --directory . -b "$(realpath build/)" --capture -o coverage.capture && \
          lcov --directory . -b "$(realpath build/)" --add-tracefile coverage.base --add-tracefile coverage.capture -o coverage.info && \
          lcov --directory . -b "$(realpath build/)" --remove coverage.info '*/unit-tests/*' -o coverage.info && \
          genhtml coverage.info -o coverage
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: unit-tests/coverage

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./unit-tests/coverage.info
          flags: unittests
          name: codecov-app-bitcoin
          fail_ci_if_error: true
          verbose: true
      
      - name: HTML documentation
        run: doxygen .doxygen/Doxyfile

      - uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: doc/html

  job_test:
    name: Tests
    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "2.1"
          - model: nanox
            SDK: "2.0.2"
          - model: nanosp
            SDK: "1.0"

    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/app-bitcoin-new/speculos-bitcoin:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin Testnet app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-app-${{matrix.model}}
          path: bin

      - name: Run tests
        run: |
          cd tests
          pip install -r requirements.txt
          PYTHONPATH=$PYTHONPATH:/speculos pytest --headless --model=${{ matrix.model }} --sdk=${{ matrix.SDK }}

  job_test_mainnet:
    name: Tests on mainnet
    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "2.1"
          - model: nanox
            SDK: "2.0.2"
          - model: nanosp
            SDK: "1.0"

    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/app-bitcoin-new/speculos-bitcoin:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-app-${{matrix.model}}
          path: bin

      - name: Run tests
        run: |
          cd tests_mainnet
          pip install -r requirements.txt
          PYTHONPATH=$PYTHONPATH:/speculos pytest --headless --model=${{ matrix.model }} --sdk=${{ matrix.SDK }}

  job_test_js_lib:
    name: Tests with the JS library
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/app-bitcoin-new/speculos-bitcoin:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Download Bitcoin Testnet app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-app-nanos
          path: bin

      - name: Run tests
        run: |
          cd bitcoin_client_js
          yarn install
          LOG_SPECULOS=1 LOG_APDUS=1 SPECULOS="/speculos/speculos.py" yarn test

  job_test_legacy_native:
    name: Legacy tests
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/app-bitcoin-new/speculos-bitcoin:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin Testnet app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-app-nanos
          path: tests-legacy/bitcoin-testnet-bin

      - name: Run tests
        run: |
          cd tests-legacy
          pip install -r requirements.txt
          PATH=$PATH:/speculos pytest


  job_test_legacy_lib:
    name: Legacy tests (library)
    needs: job_build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/app-bitcoin-new/speculos-bitcoin:latest
      ports:
        - 1234:1234
        - 9999:9999
        - 40000:40000
        - 41000:41000
        - 42000:42000
        - 43000:43000
      options: --entrypoint /bin/bash

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Download Bitcoin app binary
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-app-nanos
          path: tests-legacy/bitcoin-bin

      - name: Download Bitcoin Testnet app binary (library version)
        uses: actions/download-artifact@v2
        with:
          name: bitcoin-testnet-lib-app-nanos
          path: tests-legacy/bitcoin-testnet-bin


      - name: Run tests
        run: |
          cd tests-legacy
          pip install -r requirements.txt
          PATH=$PATH:/speculos pytest
